name: BarterSigns
main: com.dumptruckman.minecraft.bartersigns.BarterSignsPlugin
version: maven-version-number
author: dumptruckman

softdepend: [Towny]

commands:
  bs:
    description: The base command for BarterSigns
    usage: /<command>
  barter:
    description: The base command for BarterSigns
    usage: /<command>